/*let t = '{"idGame":"v9mjblgf2","idRoom":"oqly2fro3","countPlayers":2,"countBots":0,"started":true,"players":[{"name":"j","clues":[],"leader":true,"tokens":[{"val":0,"col":"black"},{"val":1,"col":"white"},{"val":1,"col":"black"},{"val":2,"col":"white"},{"val":6,"col":"black"}]},{"name":"y","clues":[{"1":3}],"leader":false,"tokens":[{"val":0,"col":"white"},{"val":3,"col":"white"},{"val":3,"col":"black"},{"val":4,"col":"black"},{"val":8,"col":"white"}]}],"turn":{"actifCard":"1","actifPlayer":"j","answered":["j","y"]},"cardsPile":[{"id":14,"label":"Ou sont tes couleurs qui se suivent","regExResponse":"[]","typeResponse":"MultipleArray"},{"id":13,"label":"Ou sont tes 8 ou tes 9","choix":["8","9"],"regExResponse":"[]","typeResponse":"Array"},{"id":9,"label":"Ou sont tes 1 ou tes 2","choix":["1","2"],"regExResponse":"[]","typeResponse":"Array"},{"id":6,"label":"Quel est la sommes des tes chiffres de gauche","regExResponse":"/[0-9]{0,2}/","typeResponse":"Number"},{"id":5,"label":"Quel est la sommes des tes chiffres du milieu","regExResponse":"/[0-9]{0,2}/","typeResponse":"Number"},{"id":12,"label":"Ou sont tes 6 ou tes 7","choix":["6","7"],"regExResponse":"[]","typeResponse":"Array"},{"id":10,"label":"Ou sont tes 3 ou tes 4","choix":["3","4"],"regExResponse":"[]","typeResponse":"Array"},{"id":2,"label":"Combien de chiffres noir as-tu","regExResponse":"/[0-5]/","typeResponse":"Number"},{"id":8,"label":"Ou sont tes 0","regExResponse":"[]","typeResponse":"Array"}],"cards":[{"id":15,"label":"Ta tuile C est-elle strictement superieur à 4","regExResponse":"/(true|false|[0-1])/i","typeResponse":"Boolean"},{"id":7,"label":"Quel est la sommes des tes chiffres de droite","regExResponse":"/[0-9]{0,2}/","typeResponse":"Number"},{"id":4,"label":"Quel est la sommes des tes chiffres noir","regExResponse":"/[0-9]{0,2}/","typeResponse":"Number"},{"id":11,"label":"Ou sont tes 5","regExResponse":"[]","typeResponse":"Array"},{"id":3,"label":"Quel est la sommes des tes chiffres blanc","regExResponse":"/[0-9]{0,2}/","typeResponse":"Number"},{"id":1,"label":"Combien de chiffres blanc as-tu","regExResponse":"/[0-5]/","typeResponse":"Number"}],"cardsDiscard":[]}';
let s = (JSON.parse(t)).cards
console.log(s);
s.forEach((c,i)=> {
  console.log(c,i);
  //if(card.id == game.turn.actifCard) game.cardsDiscard.push(game.cards.splice(k,1))
  
}) 

*/
let t = '{"idGame":"v9mjblgf2","idRoom":"oqly2fro3","countPlayers":2,"countBots":0,"started":true,"players":[{"name":"j","clues":[],"leader":true,"tokens":[{"val":0,"col":"black"},{"val":1,"col":"white"},{"val":1,"col":"black"},{"val":2,"col":"white"},{"val":6,"col":"black"}]},{"name":"y","clues":[{"1":3}],"leader":false,"tokens":[{"val":0,"col":"white"},{"val":3,"col":"white"},{"val":3,"col":"black"},{"val":4,"col":"black"},{"val":8,"col":"white"}]}],"turn":{"actifCard":null,"actifPlayer":"j","answered":[]},"cardsPile":[{"id":13,"label":"Ou sont tes 8 ou tes 9","choix":["8","9"],"regExResponse":"[]","typeResponse":"Array"},{"id":9,"label":"Ou sont tes 1 ou tes 2","choix":["1","2"],"regExResponse":"[]","typeResponse":"Array"},{"id":6,"label":"Quel est la sommes des tes chiffres de gauche","regExResponse":"/[0-9]{0,2}/","typeResponse":"Number"},{"id":5,"label":"Quel est la sommes des tes chiffres du milieu","regExResponse":"/[0-9]{0,2}/","typeResponse":"Number"},{"id":12,"label":"Ou sont tes 6 ou tes 7","choix":["6","7"],"regExResponse":"[]","typeResponse":"Array"},{"id":10,"label":"Ou sont tes 3 ou tes 4","choix":["3","4"],"regExResponse":"[]","typeResponse":"Array"},{"id":2,"label":"Combien de chiffres noir as-tu","regExResponse":"/[0-5]/","typeResponse":"Number"},{"id":8,"label":"Ou sont tes 0","regExResponse":"[]","typeResponse":"Array"}],"cards":[{"id":15,"label":"Ta tuile C est-elle strictement superieur à 4","regExResponse":"/(true|false|[0-1])/i","typeResponse":"Boolean"},{"id":7,"label":"Quel est la sommes des tes chiffres de droite","regExResponse":"/[0-9]{0,2}/","typeResponse":"Number"},{"id":4,"label":"Quel est la sommes des tes chiffres noir","regExResponse":"/[0-9]{0,2}/","typeResponse":"Number"},{"id":11,"label":"Ou sont tes 5","regExResponse":"[]","typeResponse":"Array"},{"id":3,"label":"Quel est la sommes des tes chiffres blanc","regExResponse":"/[0-9]{0,2}/","typeResponse":"Number"},[{"id":14,"label":"Ou sont tes couleurs qui se suivent","regExResponse":"[]","typeResponse":"MultipleArray"}]],"cardsDiscard":[[{"id":1,"label":"Combien de chiffres blanc as-tu","regExResponse":"/[0-5]/","typeResponse":"Number"}]]}'
let game = (JSON.parse(t))
game.players.forEach((player,k)=> {
  if (player.name == game.turn.actifPlayer) {
    console.log(k,game.players.length,game.players[k+1].name)
    game.turn.actifPlayer = (k+1 >= game.players.length?game.players[0]:game.players[k+1].name)
  }
})

